### ISSUE TITLE
Where is the .XPR file?

### ISSUE THREAD

**Issue by NLI-BobFoley** [Digilent/Arty-Z7-20-hdmi-out#3]
Instructions say to "Open the XPR project file, found at <archive extracted location>/vivado_proj/Arty-Z7-20-hdmi-out.xpr"

Neither the .XPR file nor the vivado_proj directory exist.

**Comment by 3togo** [comment]
https://github.com/Digilent/Arty-Z7-20-hdmi-out/blob/master/src/constraints/ArtyZ7_B.xdc
